Story1
julie-beaucage/Bloomingpals pull request #9
Opened 2024-09-11 21:20 UTC by julie-beaucage

2024-09-11 21:37 UTC, alexis-brosseau requested changes
- Peux-tu bouger le code dans le dossier _auth_ ?
- Remplacer les _px_ dans le css par des _em_ (sauf pour la largeur des bordures)

2024-09-11 22:44 UTC, julie-beaucage commented
Peux-tu déplacer le code dans le dossier auth ? :

Suis-je obligé de le faire, parce que cela va modifier le fichier de configuration web et les chemins ? Et il n'y a pas vraiment de différence sur l'endroit où je le mets.

Remplacer les px dans le CSS par des em (sauf pour la largeur des bordures) : 

ça ne me dérange pas de le faire cette fois-ci, mais si dans le future mon code est déjà parfaitement adaptatif, est-ce que je peux gérer le CSS moi-même ? Je veux dire si je vois que ça ne fonctionne pas, je le changerai. De toute façon ce n'est clairement pas finale, c'est juste pour que ça soit dans le projet

2024-09-11 23:03 UTC, alexis-brosseau approved these changes

2024-09-11 23:32 UTC, alexis-brosseau commented
Désolé, je pensais que c'était ta version finale. Je viens de penser à ça et j'aurais dû te dire que tu aurais aussi pu supprimer le dossier _auth_ au lieu de bouger tes trucs, tant qu'il n'y a pas 2 page de login.

Pour le CSS j'ai aucun problème pour que tu le gères toi-même tant qu'il est adaptatif. Une taille en _px_ va varier selon la résolution des écrans et donc n'est pas du tout adaptatif. C'est pour ça qu'utiliser des _%_, _em_ ou _rem_ est mieux.

2024-09-12 19:08 UTC, TheFalseCalcium reviewed
looks good. bizarre que dans ton css tu modifies tous les elem <a> et <p> tho

2024-09-12 19:08 UTC, TheFalseCalcium approved these changes

2024-09-12 19:09 UTC, merged